name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-13, macos-14 ] # 13: Intel; 14: Apple Silicon

    env:
      GOTOOLCHAIN: auto
      CGO_ENABLED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Show environment
        run: |
          go version
          go env

      - name: Install dependencies
        run: |
          go mod download

      - name: Run tests
        run: |
          make test

      - name: Build
        run: |
          make build-dist

      - name: List dist
        shell: bash # Required for Windows runner
        run: ls -la dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: localgal-${{ matrix.os }}-${{ github.sha }}
          path: dist/*
          if-no-files-found: error
